### PR TITLE
added Dyebench

### PR DESCRIPTION
**Pull request by JasperChaseTOQ**
added my new addon dyebench

### CODE REVIEW

**Review by Phoenix-Starlight — COMMENTED** [review]
Build page is missing.

**Comment by svr333** [comment]
probably just not merged yet

**Review by svr333 — APPROVED** [review]

**Comment by JasperChaseTOQ** [comment]
> probably just not merged yet

yup there is a PR to add it (as of now....)

**Review by Phoenix-Starlight — APPROVED** [review]
I see the PR now.

**Comment by JasperChaseTOQ** [comment]
thank you :D

**Pull request merged**
