### PR TITLE
Added category images

### PR DESCRIPTION
**Pull request by pentabulge**
Added an image at the top of each category page, for aesthetic purposes.
If you think this is a good idea, I may do this for other items and future categories, too.

### CODE REVIEW

**Review by LinoxGH — COMMENTED** [review]
I think this is a great addition, although I think these changes should be done for all categories before merging.

**Comment by LinoxGH** [comment]
Also there are merge conflicts that needs to be fixed.

**Review by LinoxGH — CHANGES_REQUESTED** [review]

**Comment by svr333** [comment]
If penta doesnt do these changes I will do them in a bit

**Review by LinoxGH — CHANGES_REQUESTED** [review]

**Comment by svr333** [comment]
Only images are missing now

**Comment by svr333** [comment]
Remaining missing images:
Resources
Items
Technical Components
GPS
Cargo Management
Seasonal Categories (might skip this one)
Christmas Seasonal Categories
Electric Machines

Below is an image for Items but its low quality, dont know if its worth using
backpack

**Comment by svr333** [comment]
Closing this because I dont know how to make the images and penta doesnt have time to finish this up

**Pull request closed without merging**
