### PR TITLE
Updated Weapons Category

### PR DESCRIPTION
**Pull request by KethTheMeifwa**
- Added Item Image to all Weapons
- Added Lore Image to all Weapons
- Added xp cost and whether it's a group/single research to all Weapons.
- Added Soulbound Trident to Soulbound Weapons page.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Hi! Thanks for your effort, but I am afraid that I must decline these changes.

1. I don't think adding a simple image for the item is justified in most cases here, they are mostly equivalent to the vanilla icons.
And if we ever release an official resourcepack for Slimefun, the textures might as well change.
2. Lore could theoretically be subject to change too, if item translations get finished at some point. But the main reason why I think the lore is unnecessary is that this could easily be automated for every single item via a script here, if we ever wanna display these.
3. Research costs are highly dependent on the server you are on. Lots of servers have vastly different research costs, as they are configurable. A lot of servers don't even have researches enabled.

I appreciate the idea but I think that these changes aren't really necessary as of now, especially because it would leave the other wiki pages very inconsistent.

**Comment by KethTheMeifwa** [comment]
Totally understand, I would recommend adding the Soulbound Trident though as that was entirely missing from the weapons list.

**Comment by svr333** [comment]
> 
> 
> Totally understand, I would recommend adding the Soulbound Trident though as that was entirely missing from the weapons list.

Sure! Could you make a new PR for this? (Or rename this PR and revert all the changes except that one)

**Comment by svr333** [comment]
Reverted everything apart from the Soulbound Trident addition to the Soulbound-Weapons page

**Review by svr333 — APPROVED** [review]

**Review by Sfiguz7 — APPROVED** [review]

**Pull request merged**
