### PR TITLE
Add Bump

### PR DESCRIPTION
**Pull request by ybw0014**
Hi, it's Bump again.
This time I mark the builds as third-party so users can distinguish.
Guizhan Builds holds projects of @SlimefunGuguProject (a Simplified Chinese translation group), which is similar to TheBusyBiscuit's builds page. It is fully open-source too (https://github.com/ybw0014/maven-builds).

### CODE REVIEW

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
As mentioned in my last PR, I am currently blocking this until we internally agreed upon our stance on third-party download links.

**Comment by ybw0014** [comment]
Hi, how is the discussion about third-party download link?

**Comment by ybw0014** [comment]
Ok, we decide to move.

**Review by Phoenix-Starlight — DISMISSED** [review]

**Comment by svr333** [comment]
build page is currently invalid

**Comment by ybw0014** [comment]
biscuit has not merged my pr to builds yet

**Comment by svr333** [comment]
we'll await that

**Comment by TheBusyBiscuit** [comment]
I am sorry that you haven't heard back in a while. It's been quite busy.
As I told you, I wanted to discuss this with the other staff members first.
The general consensus was that we would like to allow your site to be posted there. There would simply be two requirements:
1. The site must be available in english
2. The link must be clearly labelled as "Builds (via Third-Party site)"

But in general we would like you to use whichever site you prefer, so if these two requirements are fulfilled, feel free to change it back to your own link. From what I can tell parts of the site are available in english already.

**Comment by ybw0014** [comment]
My builds page was designed to serve Chinese users only, so everything was in Chinese only. I added i18n module days ago, now my builds page can be displayed in both Chinese and English, except for the announcement and status image.

**Review by Phoenix-Starlight — APPROVED** [review]
Other than the pages that you already mentioned, it's good.

**Review by Sefiraat — APPROVED** [review]
Marked as third party and offered in enough English for users to be able to navigate and know what they’re downloading, looks good to me :)

**Review by svr333 — APPROVED** [review]

**Pull request merged**
