### PR TITLE
Removed abandoned add-ons from the Wiki and fixed auto enchanter and auto disenchanter wiki

### PR DESCRIPTION
**Pull request by PhoenixCodingStuff**
Removed ClayTech and GeneticChickenEngineering 
And fixed auto enchanter and auto disenchanter wiki ( Added tier 2 for both and fixed a typo on disenchanter wiki )

### CODE REVIEW

**Comment by Sefiraat** [comment]
Hey Phoenix, you should remove the Auto Enchant from here and raise that in a separate PR. PR's should stay in their original scope.

**Comment by PhoenixCodingStuff** [comment]
um how do I do that , I was going to create a new PR but it directly added it here

**Comment by PhoenixCodingStuff** [comment]
okay next time ill keep in mind to make new fork for each PR :D

**Comment by svr333** [comment]
no no not a new fork, wont work if you use the same branch
this was written quickly and dirty, might be better to look for a guide/tutorial online

basically you branch into stuff
`git checkout -b RemoveAbandonedAddons`

you do your changes regarding that, you then
`git commit -am "Fixxy fix"`
`git push`

and then if you go on Slimefun/Wiki github itll say "recent changes to RemoveAbandonedAddons, create a PR?"

and go ahead
then I go back to master branch
`git checkout master`

and while your previous PR is still open, you can work on a new one with:
`git checkout -b FixAuto(dis)enchanter`

*do changes*

`git commit -am "Ah."`
`git push`

and you can repeat infinite times.

--------------

If at some point you have to edit an old one, you can:
`git checkout RemoveAbandonedAddons`
do your changes, commit, push and itll automatically update to the currently open PR

**Comment by Phoenix-Starlight** [comment]
Github has some interfaces/aliases for what svr333 said. Otherwise if you're running on low-budget notebooks its going to be pretty painful to accomplish without using lightweight distributions. (Windows I don't count because its 20 GB or so and that adds up very fast). Click the branch called 'main' or master. (master is old convention) and type in desired name. Github will offer to create a branch from the current branch you are in. Then make your desired changes (and commit to that branch!). Then you can finally PR as said. Then once its pulled it feel free to do whatever with the now spare branch, and sync your main branch.

Merge conflicts might occur, so you may end up having to clone as said.

**Review by Phoenix-Starlight — APPROVED** [review]

**Comment by PhoenixCodingStuff** [comment]
ohh ok ty for the info , I'm new to GitHub so I didn't know all this stuff

**Comment by svr333** [comment]
I didnt realize I was talking to two different people until just now 😓

**Review by svr333 — APPROVED** [review]
Thank you for your contribution!
It is greatly appreciated

**Pull request merged**
