### PR TITLE
Clean up Carbon Pages

### PR DESCRIPTION
**Pull request by svr333**

### CODE REVIEW

**Review by TheBusyBiscuit — COMMENTED** [review]
The name "CARBONS" is quite off though, didn't even notice that.
Should rather just be "CARBON".

**Comment by svr333** [comment]
Sure, I just named it carbons cuz theres multiple carbon variants

**Review by Phoenix-Starlight — APPROVED** [review]
LGTM

**Review by TheBusyBiscuit — APPROVED** [review]
LGTM

**Review by Sfiguz7 — APPROVED** [review]
Looks good

**Pull request merged**
