### PR TITLE
add Supreme and abandoned SupremeExpansion

### PR DESCRIPTION
**Pull request by RelativoBR**
Reason: due to changes that will break the current items, I'm stopping the old addon and creating a new version
(https://github.com/TheBusyBiscuit/builds/pull/190)

### CODE REVIEW

**Comment by RelativoBR** [comment]
I'm in contact with some server owners, it's possible to update the old one to the new one, there is already a config.yml option for that.

I had several private addons, and I gathered them all as supreme 2.0, in addition there is a new mutation system for generating the cloning of items.

I'm transforming the addon into something more dynamic, where the items generated by the machines are in confog.yml, allowing people to add new ones or remove items they don't want. (I already applied this to the quarry)

I'm going to prepare a wiki, because in my opinion this will be the addon with the most features and dynamic options to customize. I even got an idea of the translations of the last addon that came out, and it will be possible to have Supreme 2.0 in any language.

Note:
This addon "Supreme 2.0" compatible with the old addon "SupremeExpansion" change in config use-legacy-supremeexpansion-item-id to true

**Comment by Phoenix-Starlight** [comment]
Why not keep as SupremeExpansion 2.0? It's a major change so that should be
appropriate to do.

**Comment by RelativoBR** [comment]
I'm actually treating it as "SupremeExpansion" turning into something new "Supreme"... as if it were really another addon.

the idea is that the "SupremeExpansion" dies

**Comment by RelativoBR** [comment]
# #changelogs - Supreme ##
## Inclusion of new machines
- Forge Ingot - This machine allows you to forge ingot resources
- Forge Magical - This machine allows you to forge magical resources
- Foundry - Foundry and Synthesizer Items
- Magic Altar - Craft Rune and Magical Items
- Mob Collector - This machine allows you to collect items from nearby mobs
- Virtual Aquarium - This machine allows you to collect items that are collected at sea
- Virtual Garden - This machine allows you to cultivate some resources
- Cobblestone Quarry - Generate Cobblestone
## Inclusion new generator
- GeneratorMob - Generates energy from methane generated by animals
## Inclusion of new machines Tech - for cloning mechanics, evolutions and mutations
- MobTech Collector - This machine allows you to collect MobTech head nearby mobs
- Tech Mutation - Use generator mutation to progress to higher levels
- Tech Robotic - Use beginner level robots to progress to higher levels
- Tech Generator - Using power and bees/golem, slowly generates materials
## Inclusion of new items
- Cards - Used to generate resources in tech machines
- MobTech - Used to scale up Tech Generator production
## New configuration options
- use-legacy-supremeexpansion-item-id - Indication use compatibily old item from addon SupremeExpanssion
- limit-production-generators - To reduce the efficiency of generators (factor 5x)
- limit-production-quarry - To reduce quarry production (hard mode 50% failure)

**Review by Sefiraat — APPROVED** [review]
Uh, this isn't the place for your changelog? 
But regardless, this is your change to make and the links/content seem fine to me, so approved I guess.

**Comment by RelativoBR** [comment]
@svr333 in short, the "SupremeExpansion" addon has been discontinued, and a new "Supreme" addon has appeared (has the features of the old addon and more...)

**Review by Phoenix-Starlight — APPROVED** [review]
Approved.

**Pull request merged**
