### PR TITLE
Henrylvdb wiki ready

### PR DESCRIPTION
**Pull request by henrylvdb**

### CODE REVIEW

**Review by TheBusyBiscuit — COMMENTED** [review]
This is just full of placeholders and todos, it does not seem "ready" to me.

**Comment by Phoenix-Starlight** [comment]
Do we really need a page for compressed carbon, there's already a carbon page listing all carbon based resources. Also you need to fill your files in.

**Comment by henrylvdb** [comment]
Ok, I will do my best to finish what I can. Would anybody like to help me with this?

**Comment by Phoenix-Starlight** [comment]
> Ok, I will do my best to finish what I can. Would anybody like to help me with this?

I think you're supposed to do it yourself, submit it for review and then it will be approved.

**Pull request closed without merging**
