### PR TITLE
Fix broken ItemHandler link

### PR DESCRIPTION
**Pull request by Bunnky**

### CODE REVIEW

**Review by Phoenix-Starlight — APPROVED** [review]
Looks good to me.

**Review by Sefiraat — APPROVED** [review]
Apart from @Bunnky being the source, looks perfect to me :)

**Comment by Phoenix-Starlight** [comment]
Actually I'll just comb through git to see whether it's the same or not.

**Review by Phoenix-Starlight — APPROVED** [review]
Yep, looks good, just relocation of the class.

**Pull request merged**
