### PR TITLE
Add Gastronomicon

### PR DESCRIPTION
**Pull request by SchnTgaiSpock**

### CODE REVIEW

**Review by Phoenix-Starlight — DISMISSED** [review]
Just a quick question: Why the 1 character addition of a back slash?

**Comment by SchnTgaiSpock** [comment]
oh thats weird, i think my editor did that on save

**Comment by SchnTgaiSpock** [comment]
ah it was the markdown formatter

**Review by Phoenix-Starlight — APPROVED** [review]
Looking good

**Review by svr333 — APPROVED** [review]

**Pull request merged**
